### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ronniemukherjee** [elsix/angular-jointjs-graph-demo#4] opened 2015-09-06 11:29 UTC
When I'm trying to drag onto the canvas I'm getting an error (see screenshot)

![image](https://cloud.githubusercontent.com/assets/11668348/9704126/eb65cdfe-5492-11e5-89ca-1baacbcb30b3.png)

**Comment by ronniemukherjee** [comment] 2015-09-06 11:44
See Line 4972 in joint.nojquerynobackbone.js, it is returning undefined

var size = this.model.get('size');

**Comment by npetkov** [comment] 2015-09-06 12:40
I hope to have figured out the problem by tomorrow. Thanks for your feedback!

**Comment by npetkov** [comment] 2015-09-08 09:48
Could you please provide the following information about your setup:
- is this a clean deployment of the app, or have you made some modifications to the sources?
- what database adapter are you using?

Beyond that, could you please also attach the complete stack traces you're seeing since I wasn't able to reproduce the problem upon a clean start of the app.

**Comment by ronniemukherjee** [comment] 2015-09-08 15:48
Hi

It is a clean install and I am running mongodb.

When running bower install I get the following questions

Unable to find a suitable version for lodash, please choose one:
    1) lodash#^2.4.1 which resolved to 2.4.1 and is required by dagre#0.7.1, graphlib#1.0.1 
    2) lodash#2.4.1 which resolved to 2.4.1 and is required by joint#0.9.4 
    3) lodash#^3.2.0 which resolved to 3.10.1 and is required by angular-jointjs-graph#0.1.7Prefix the choice with ! to persist it to bower.json

Unable to find a suitable version for jquery, please choose one:
    1) jquery#2.0.3 which resolved to 2.0.3 and is required by joint#0.9.4 
    2) jquery#^2.1.3 which resolved to 2.1.4 and is required by angular-jointjs-graph#0.1.7Prefix the choice with ! to persist it to bower.json

...how I answer these questions influences the nature of the error. I will post stack trace now.

**Comment by ronniemukherjee** [comment] 2015-09-08 15:53
Answering 2 to both questions:

Unable to find a suitable version for jquery, please choose one:
    1) jquery#2.0.3 which resolved to 2.0.3 and is required by joint#0.9.4 
    2) jquery#^2.1.3 which resolved to 2.1.4 and is required by angular-jointjs-graph#0.1.7Prefix the choice with ! to persist it to bower.json

? Answer:: 2

Unable to find a suitable version for lodash, please choose one:
    1) lodash#^2.4.1 which resolved to 2.4.1 and is required by dagre#0.7.1, graphlib#1.0.1 
    2) lodash#2.4.1 which resolved to 2.4.1 and is required by joint#0.9.4 
    3) lodash#^3.2.0 which resolved to 3.10.1 and is required by angular-jointjs-graph#0.1.7Prefix the choice with ! to persist it to bower.json

? Answer:: 2

...gives following stack trace:

TypeError: Cannot read property 'Rect' of undefined
    at Object.init (angular-jointjs-graph.js:1209)
    at initGraph (angular-jointjs-graph.js:167)
    at controller.$scope.$on.data.graph.$get.then.then.then.then.$scope.$emit.errData (angular-jointjs-graph.js:160)
    at angular.js:14634
    at m.a.$get.m.$eval (angular.js:15878)
    at m.a.$get.m.$digest (angular.js:15689)
    at m.a.$get.m.$apply (angular.js:15986)
    at g (angular.js:10511)
    at L (angular.js:10683)
    at XMLHttpRequest.A.onload (angular.js:10624)

**Comment by npetkov** [comment] 2015-09-10 12:35
Hi, it looks like there is a breaking change in jointjs 0.9.4 (should be a minor revision, but go figure). If you're curious, [here](https://github.com/clientIO/joint/commit/4683184#diff-f71ceb02b58439b19181df20e2484a06R337) is line that causes the stack trace you're seing. It seems jointjs now uses the 'size' property of the model instead of the element's bounding box. I'd advise you to manually downgrade to jointjs 0.9.3 for the moment as I don't see an immediate fix to this problem.

**Comment by ronniemukherjee** [comment] 2015-09-10 12:49
Ok Nikolay thanks for looking into this and I will downgrade to 0.9.3 as you suggest.

**Comment by PatHuman** [comment] 2015-10-23 09:03
Hi,
Would it be possible to have a guide on setting  up the demo... i had to manually add joint.nojquerynobackbone.min.js |min.css, it loads fine, but then throws errors when i click.  it doesn't feel right, maybe i miss some adjustments..
Cheers

**Comment by npetkov** [comment] 2015-10-23 15:29
Normally, following the four steps listed in the readme would be sufficient. However, due to a known issue with jointjs 0.9.4 (see above comments) you will have to manually downgrade it to 0.9.3 after running `bower install`. I'm aware that this is inconvenient but upgrading the jointjs version requires a serious refactoring/redesign of the `angular-jointjs-graph` framework which I lack time to undertake currently.

**Comment by PatHuman** [comment] 2015-10-23 20:56
Thanks mate, i did miss that one above. me--, npetkov++

**Comment by npetkov** [comment] 2015-12-22 17:26
Should be fixed with the latest release of the supporting library.

**Closed as completed by npetkov** 2015-12-22 17:26 UTC
